#!/bin/bash

set -e

if [ $# != 1 ] ; then
echo "ERROR: Missing required param 'version'."
echo "eg.: $0 0.0.1"
exit 1;
fi

../build 
wait
if [ $? -ne 0 ]; then
    exit $?
fi

cd ./docker

IMAGE_NAME="tzfun/etcd-workbench:$1"

echo Building dockerfile...
echo $IMAGE_NAME
docker build -f Dockerfile -t $IMAGE_NAME . 
wait
if [ $? -ne 0 ]; then
    exit $?
fi

echo Pushing image $IMAGE_NAME
docker push $IMAGE_NAME
wait